/**
 * Hindi for the franchise side, keyed by the English exactly as it appears in
 * the code (see contexts/LanguageContext). A line missing here simply shows in
 * English. Words franchise owners already use in English — warranty, lead,
 * order, invoice, stock, POSM, PPF — stay as they are, in Devanagari.
 */
export const HI: Record<string, string> = {
    /* ---- Sidebar groups and pages ---- */
    "Core": "मुख्य",
    "Operations": "कामकाज",
    "Support": "सहायता",
    "Team & Performance": "टीम और प्रदर्शन",
    "Home": "होम",
    "Channel Partner Home": "होम",
    "My Profile": "मेरी प्रोफ़ाइल",
    "Warranty Management": "वारंटी",
    "My Leads": "मेरी लीड",
    "E-Catalogue": "ई-कैटलॉग",
    "Product Catalogue": "प्रोडक्ट कैटलॉग",
    "POSM Requirements": "POSM सामग्री",
    "Order Management": "ऑर्डर",
    "Offers & Schemes": "ऑफ़र और स्कीम",
    "Audit & Compliance": "ऑडिट",
    "News & Alerts": "समाचार और अलर्ट",
    "Grievance Redressal": "शिकायत",
    "Terms & Conditions": "नियम और शर्तें",
    "Claim Process": "क्लेम प्रक्रिया",
    "Manpower Control": "स्टाफ़",
    "Targets & Achievements": "लक्ष्य और उपलब्धि",
    "Product Details": "प्रोडक्ट विवरण",
    "Category View": "कैटेगरी",
    "Dashboard": "डैशबोर्ड",
    "Soon": "जल्द",
    "Sign Out": "लॉग आउट",
    "Partner": "पार्टनर",
    "Franchise Portal": "फ़्रैंचाइज़ पोर्टल",
    "Distributor Portal": "डिस्ट्रीब्यूटर पोर्टल",
    "Distributor / Franchise Dashboard": "डिस्ट्रीब्यूटर / फ़्रैंचाइज़ डैशबोर्ड",

    /* ---- Top bar ---- */
    "Franchise": "फ़्रैंचाइज़",
    "Distributor": "डिस्ट्रीब्यूटर",
    "Distributor / Franchise": "डिस्ट्रीब्यूटर / फ़्रैंचाइज़",
    "Management Suite": "मैनेजमेंट",

    /* ---- My Leads ---- */
    "Customer": "ग्राहक",
    "Product": "प्रोडक्ट",
    "Car": "कार",
    "Date": "तारीख",
    "Area": "इलाका",
    "Status": "स्थिति",
    "From": "से",
    "To": "तक",
    "to": "से",
    "Last 30 days": "पिछले 30 दिन",
    "This month": "इस महीने",
    "Last month": "पिछला महीना",
    "All time": "शुरू से अब तक",
    "Custom": "अपनी तारीख",
    "Copy number": "नंबर कॉपी करें",
    "Number copied": "नंबर कॉपी हो गया",
    "Loading your leads…": "आपकी लीड लोड हो रही हैं…",
    "Customers Autoform sent to your store. Our team calls every customer back, and the status shows how each one went.": "वे ग्राहक जिन्हें Autoform ने आपके स्टोर पर भेजा। हमारी टीम हर ग्राहक को वापस कॉल करती है, और स्थिति बताती है कि बात कैसी रही।",
    "Leads": "लीड",
    "since your first lead": "आपकी पहली लीड से",
    "Won": "पक्की हुई",
    "Conversion": "कन्वर्ज़न",
    "once our team has called your leads": "टीम के कॉल करने के बाद दिखेगा",
    "won out of customers called": "कॉल किए गए ग्राहकों में से पक्की",
    "To follow up": "फिर से कॉल करें",
    "customers still deciding — call them": "ग्राहक अभी सोच रहे हैं — उन्हें कॉल करें",
    "nobody waiting": "कोई बाकी नहीं",
    "How your leads ended": "आपकी लीड का नतीजा",
    "Follow up": "फिर से कॉल",
    "Lost": "नहीं हुई",
    "No answer": "जवाब नहीं मिला",
    "Not called yet": "अभी कॉल नहीं हुई",
    "Leads over time": "समय के साथ लीड",
    "by week": "हफ़्ते के हिसाब से",
    "by day": "दिन के हिसाब से",
    "No leads in this period.": "इस समय में कोई लीड नहीं।",
    "The chart appears once you have a few more leads in this period.": "इस समय में कुछ और लीड आने पर चार्ट दिखेगा।",
    "Other leads": "बाकी लीड",
    "No leads yet": "अभी कोई लीड नहीं",
    "No leads here": "यहाँ कोई लीड नहीं",
    "When a customer picks your store on WhatsApp, or our team sends a customer to you, they will appear here — with how the call went.": "जब कोई ग्राहक WhatsApp पर आपका स्टोर चुनेगा, या हमारी टीम कोई ग्राहक आपके पास भेजेगी, तो वह यहाँ दिखेगा — कॉल कैसी रही, उसके साथ।",
    "Nothing matches this period and outcome. Try another period, or tap Leads to see them all.": "इस समय और नतीजे में कुछ नहीं मिला। कोई और समय चुनें, या सब देखने के लिए 'लीड' पर टैप करें।",

    /* ---- Offers & Schemes ---- */
    "Live": "चालू",
    "Upcoming": "आने वाली",
    "Draft": "ड्राफ़्ट",
    "Closed": "बंद",
    "Under review": "जाँच में",
    "Approved": "मंज़ूर",
    "Not approved": "मंज़ूर नहीं",
    "Sales": "सेल्स",
    "Display": "डिस्प्ले",
    "Contest": "प्रतियोगिता",
    "Offer": "ऑफ़र",
    "No more windows": "अब कोई समय नहीं",
    "Ends today": "आज खत्म",
    "Could not load schemes": "स्कीम लोड नहीं हो सकीं",
    "Try again": "फिर से कोशिश करें",
    "Loading schemes…": "स्कीम लोड हो रही हैं…",
    "Join a scheme, submit your invoices and see what you've earned.": "स्कीम से जुड़ें, अपने इनवॉइस जमा करें और देखें आपने क्या कमाया।",
    "Running": "चालू",
    "Coming up": "आने वाली",
    "Past": "पुरानी",
    "Refresh": "रीफ़्रेश",
    "No schemes running": "अभी कोई स्कीम नहीं चल रही",
    "Nothing coming up": "कोई आने वाली स्कीम नहीं",
    "No past schemes": "कोई पुरानी स्कीम नहीं",
    "New schemes appear here, and you'll get a notification when one starts.": "नई स्कीम यहाँ दिखेंगी, और शुरू होने पर आपको सूचना मिलेगी।",
    "Points": "पॉइंट",
    "points": "पॉइंट",
    "pts": "पॉइंट",
    "Club": "क्लब",
    "Clubs": "क्लब",
    "Rank": "रैंक",
    "Ranks": "रैंक",
    "You've joined. Your points show here once an entry is approved.": "आप जुड़ गए हैं। एंट्री मंज़ूर होते ही आपके पॉइंट यहाँ दिखेंगे।",
    "View details": "पूरी जानकारी",
    "Submit invoice": "इनवॉइस जमा करें",
    "Join scheme": "स्कीम से जुड़ें",
    "Could not open the scheme": "स्कीम खुल नहीं सकी",
    "My entries": "मेरी एंट्री",
    "Rewards & clubs": "इनाम और क्लब",
    "Rewards": "इनाम",
    "How it works": "कैसे काम करती है",
    "Leaderboard": "लीडरबोर्ड",
    "Terms": "शर्तें",
    "You've joined": "आप जुड़ गए हैं",
    "Submit your invoices from here.": "अपने इनवॉइस यहाँ से जमा करें।",
    "Could not join": "जुड़ नहीं सके",
    "All schemes": "सभी स्कीम",
    "See the latest approvals and your rank": "ताज़ा मंज़ूरी और अपना रैंक देखें",
    "See full poster": "पूरा पोस्टर देखें",
    "open now": "अभी खुला",
    "This scheme takes one entry per store, and yours is in.": "इस स्कीम में हर स्टोर की एक ही एंट्री होती है, और आपकी जा चुकी है।",
    "You can submit when the next window opens:": "अगला समय खुलने पर आप जमा कर सकते हैं:",
    "terms & conditions": "नियम और शर्तें",
    "Join to start submitting your invoices.": "इनवॉइस जमा करना शुरू करने के लिए जुड़ें।",
    "Join this scheme": "इस स्कीम से जुड़ें",
    "This scheme has closed.": "यह स्कीम बंद हो चुकी है।",
    "Questions?": "कोई सवाल?",
    "Reward": "इनाम",
    "Your points": "आपके पॉइंट",
    "Not in a club yet": "अभी किसी क्लब में नहीं",
    "Approved entries": "मंज़ूर एंट्री",
    "Counts once approved": "मंज़ूर होने पर गिनी जाएगी",
    "Reward earned": "मिला इनाम",
    "Points by month": "महीने के हिसाब से पॉइंट",
    "No instructions.": "कोई निर्देश नहीं।",
    "No terms for this scheme.": "इस स्कीम की कोई शर्त नहीं।",
    "This is an offer for information — there's no reward to earn.": "यह सिर्फ़ जानकारी के लिए ऑफ़र है — इसमें कोई इनाम नहीं।",
    "YOU'RE HERE": "आप यहाँ हैं",
    "Rewards by score": "स्कोर के हिसाब से इनाम",
    "Prizes by rank": "रैंक के हिसाब से इनाम",
    "Score": "स्कोर",
    "and above": "और उससे ज़्यादा",
    "Points per set": "हर सेट पर पॉइंट",
    "Only approved entries count.": "सिर्फ़ मंज़ूर एंट्री गिनी जाती हैं।",
    "No approved entries yet.": "अभी कोई एंट्री मंज़ूर नहीं।",
    "Show entries from": "किस दिन की एंट्री",
    "All dates": "सभी तारीखें",
    "Custom range…": "अपनी तारीखें…",
    "No entries yet": "अभी कोई एंट्री नहीं",
    "Submit an invoice to start earning points.": "पॉइंट कमाने के लिए इनवॉइस जमा करें।",
    "No entries on these dates.": "इन तारीखों पर कोई एंट्री नहीं।",
    "No entries on this date.": "इस तारीख पर कोई एंट्री नहीं।",
    "Download the poster": "पोस्टर डाउनलोड करें",
    "Entry": "एंट्री",
    "if approved": "मंज़ूर होने पर",
    "Reason": "कारण",
    "You": "आप",
    "YOU": "आप",
    "Opening the invoice": "इनवॉइस खुल रहा है",
    "Getting the reader ready": "रीडर तैयार हो रहा है",
    "Reading the invoice": "इनवॉइस पढ़ा जा रहा है",
    "Entry submitted": "एंट्री जमा हो गई",
    "It counts once it's approved.": "मंज़ूर होने पर गिनी जाएगी।",
    "Could not submit": "जमा नहीं हो सका",
    "Drop the invoice here, or": "इनवॉइस यहाँ डालें, या",
    "Drop the file here, or": "फ़ाइल यहाँ डालें, या",
    "tap to choose": "चुनने के लिए टैप करें",
    "Remove file": "फ़ाइल हटाएँ",
    "What's on the invoice": "इनवॉइस में क्या है",
    "Read again": "फिर से पढ़ें",
    "Couldn't find this scheme's series on the invoice — add them below.": "इनवॉइस में इस स्कीम की सीरीज़ नहीं मिली — नीचे जोड़ें।",
    "Couldn't read this file — add the series below.": "यह फ़ाइल पढ़ी नहीं जा सकी — नीचे सीरीज़ जोड़ें।",
    "Series": "सीरीज़",
    "Qty": "मात्रा",
    "Quantity": "मात्रा",
    "Read from": "यहाँ से पढ़ा",
    "Please check": "कृपया जाँचें",
    "Remove": "हटाएँ",
    "Add series": "सीरीज़ जोड़ें",
    "Total": "कुल",
    "Our team checks these against your invoice before the points count.": "पॉइंट गिनने से पहले हमारी टीम इन्हें आपके इनवॉइस से मिलाती है।",
    "The distributor you bought from": "जिस डिस्ट्रीब्यूटर से खरीदा",
    "Other…": "कोई और…",
    "Distributor name": "डिस्ट्रीब्यूटर का नाम",
    "Choose": "चुनें",
    "Cancel": "रद्द करें",
    "Review & submit": "देखें और जमा करें",
    "Submit this entry?": "यह एंट्री जमा करें?",
    "Check it once more — you can't change an entry after sending it.": "एक बार और जाँच लें — भेजने के बाद एंट्री बदली नहीं जा सकती।",
    "Points if approved": "मंज़ूर होने पर पॉइंट",
    "Some lines were marked to check and haven't been changed. Make sure they match your invoice.": "कुछ लाइनें जाँचने के लिए निशान लगी थीं और बदली नहीं गईं। पक्का करें कि वे आपके इनवॉइस से मेल खाती हैं।",
    "Go back and edit": "वापस जाकर बदलें",
    "Yes, submit": "हाँ, जमा करें",

    /* ---- Audit ---- */
    "Could not load your audits": "आपके ऑडिट लोड नहीं हो सके",
    "Please try again in a moment": "थोड़ी देर में फिर कोशिश करें",
    "Loading your audits…": "आपके ऑडिट लोड हो रहे हैं…",
    "The store audits you have completed, and what you answered.": "आपके पूरे किए गए स्टोर ऑडिट, और आपने क्या जवाब दिए।",
    "Audit pending": "ऑडिट बाकी है",
    "No audits yet": "अभी कोई ऑडिट नहीं",
    "When you complete a store audit on WhatsApp, your answers will appear here so you always have a record of what was submitted.": "जब आप WhatsApp पर स्टोर ऑडिट पूरा करेंगे, तो आपके जवाब यहाँ दिखेंगे, ताकि आपके पास हमेशा रिकॉर्ड रहे।",
    "Store audit": "स्टोर ऑडिट",
    "By phone": "फ़ोन पर",
    "Submitted": "जमा हो गया",
    "Your score": "आपका स्कोर",
    "Marks lost on:": "यहाँ नंबर कटे:",
    "Full marks on every question.": "हर सवाल पर पूरे नंबर।",
};
